### PR TITLE
Implements GetModerators method

### PR DESCRIPTION
**Pull request by Maniarr**
Add `GetModerators` method to use endpoint [`/moderation/moderators`](https://dev.twitch.tv/docs/api/reference#get-moderators)

### CODE REVIEW

**Comment by nicklaw5** [comment]
@Maniarr can you please resolve the merge conflicts? There are some conflicts that need resolving after merging #164.

**Comment by Maniarr** [comment]
@nicklaw5 I have resolved the conflict.

**Comment by nicklaw5** [comment]
Tests are now failing. Including two tests introduced in #164 that were passing when that PR was merged. Please try to resolve failing tests.

**Comment by Maniarr** [comment]
I added `Context` declaration in the client instantiation for the 3 tests. The change comes from #160

**Review by nicklaw5 — APPROVED** [review]

**Pull request merged**
