### PR TITLE
ci: remove travis in favor of github actions

### LINKED ISSUE #36: Use GitHub Actions instead of TravisCI for running tests

### PR DESCRIPTION
**Pull request by jbpratt**
The only additional thing required should be a token placed in the
settings for goveralls

closes #36

https://github.com/mattn/goveralls#github-actions
https://github.com/actions/setup-go/issues/31

### CODE REVIEW

**Comment by nicklaw5** [comment]
Looks good :+1: 

I've removed the Travis-CI integration and have added a secret called `COVERALLS_TOKEN` for the Coverall token. Please update the workflow to suit the new secret name.

**Comment by jbpratt** [comment]
> Looks good +1
> 
> I've removed the Travis-CI integration and have added a secret called `COVERALLS_TOKEN` for the Coverall token. Please update the workflow to suit the new secret name.

Done! I wasn't able to test this locally due to restrictions with [Act](https://github.com/nektos/act) (the images they use are inaccurate), so hopefully things work without issue but happy to fix whatever isn't working as expected.

**Comment by nicklaw5** [comment]
I would have thought a Actions runner would have been triggered but it didn't :thinking:

**Comment by nicklaw5** [comment]
I'll merge and see what happens.

**Review by nicklaw5 — APPROVED** [review]

**Comment by jbpratt** [comment]
Oops, I see that error, the cov file needs to be swapped, I believe.

Looks to be working though, besides that!

**Comment by nicklaw5** [comment]
Sweet, can you also replace the build badge in the readme with the new one for Actions?

**Comment by jbpratt** [comment]
> Sweet, can you also replace the build badge in the readme with the new one for Actions?

Sure thing, doing so now. I do agree that it should have kicked something off, and was looking for it initially but it never happened.

**Pull request merged**
